# Grilla de colores

Se tiene una grilla de cuadrados de 9×9, cada uno comienza pintado aleatoriamente de rojo o azul. 

<img src="grilla.jpg" width="200">
Se quiere pintar algunos cuadrados de manera que si se divide la grilla total en sub-grillas de 3x3 cada una de estas sub-grillas contenga cuadrados del mismo color pero el color de cada sub-grilla sea diferente que el de las subgrillas adyacentes.
<table>
    <tr>
        <td><img src="grilla-solucion-1.jpg" width="200"></td>
        <td><img src="grilla-solucion-2.jpg" width="200"></td>
    </tr>
</table>

Resolver el problema de manera que no sea necesario pintar un cuadrado más de una vez y se pinte la cantidad mínima de cuadrados




In [1]:
import numpy as np
solution1 = np.array([
[0,0,0,1,1,1,0,0,0],[0,0,0,1,1,1,0,0,0],[0,0,0,1,1,1,0,0,0],
[1,1,1,0,0,0,1,1,1],[1,1,1,0,0,0,1,1,1],[1,1,1,0,0,0,1,1,1],
[0,0,0,1,1,1,0,0,0],[0,0,0,1,1,1,0,0,0],[0,0,0,1,1,1,0,0,0], 
])
print(solution1)
solution2 = np.array([
[1,1,1,0,0,0,1,1,1],[1,1,1,0,0,0,1,1,1],[1,1,1,0,0,0,1,1,1],
[0,0,0,1,1,1,0,0,0],[0,0,0,1,1,1,0,0,0],[0,0,0,1,1,1,0,0,0],
[1,1,1,0,0,0,1,1,1],[1,1,1,0,0,0,1,1,1],[1,1,1,0,0,0,1,1,1],
])
print(solution2)

[[0 0 0 1 1 1 0 0 0]
 [0 0 0 1 1 1 0 0 0]
 [0 0 0 1 1 1 0 0 0]
 [1 1 1 0 0 0 1 1 1]
 [1 1 1 0 0 0 1 1 1]
 [1 1 1 0 0 0 1 1 1]
 [0 0 0 1 1 1 0 0 0]
 [0 0 0 1 1 1 0 0 0]
 [0 0 0 1 1 1 0 0 0]]
[[1 1 1 0 0 0 1 1 1]
 [1 1 1 0 0 0 1 1 1]
 [1 1 1 0 0 0 1 1 1]
 [0 0 0 1 1 1 0 0 0]
 [0 0 0 1 1 1 0 0 0]
 [0 0 0 1 1 1 0 0 0]
 [1 1 1 0 0 0 1 1 1]
 [1 1 1 0 0 0 1 1 1]
 [1 1 1 0 0 0 1 1 1]]


In [2]:
grilla = np.random.randint(low=0,high=2,size=(9,9))
print(grilla)

[[0 0 0 0 1 0 1 0 0]
 [0 1 0 0 0 1 1 1 0]
 [0 0 1 1 1 0 1 0 1]
 [1 0 1 0 1 1 1 1 0]
 [1 1 0 1 0 0 0 0 1]
 [1 0 0 0 1 1 0 1 1]
 [0 0 1 0 0 1 0 0 0]
 [1 0 0 1 1 0 1 0 0]
 [0 0 0 0 0 1 0 0 0]]


In [3]:
pinted = 0
for x in range(0, grilla.shape[0]):
    for y in range(0, grilla.shape[1]):
        if grilla[x][y] != solution1[x][y]:
             grilla[x][y] = solution1[x][y]
             pinted += 1
print("Cantidad de cuadros pintados: " + str(pinted))
print(grilla)

pinted = 0
for x in range(0, grilla.shape[0]):
    for y in range(0, grilla.shape[1]):
        if grilla[x][y] != solution2[x][y]:
             grilla[x][y] = solution2[x][y]
             pinted += 1
print("Cantidad de cuadros pintados: " + str(pinted))
print(grilla)

Cantidad de cuadros pintados: 33
[[0 0 0 1 1 1 0 0 0]
 [0 0 0 1 1 1 0 0 0]
 [0 0 0 1 1 1 0 0 0]
 [1 1 1 0 0 0 1 1 1]
 [1 1 1 0 0 0 1 1 1]
 [1 1 1 0 0 0 1 1 1]
 [0 0 0 1 1 1 0 0 0]
 [0 0 0 1 1 1 0 0 0]
 [0 0 0 1 1 1 0 0 0]]
Cantidad de cuadros pintados: 81
[[1 1 1 0 0 0 1 1 1]
 [1 1 1 0 0 0 1 1 1]
 [1 1 1 0 0 0 1 1 1]
 [0 0 0 1 1 1 0 0 0]
 [0 0 0 1 1 1 0 0 0]
 [0 0 0 1 1 1 0 0 0]
 [1 1 1 0 0 0 1 1 1]
 [1 1 1 0 0 0 1 1 1]
 [1 1 1 0 0 0 1 1 1]]
